version: '3'
services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - courses
    volumes:
      - ./api-gateway:/app
    networks:
      - backend

  calendar:
    container_name: calendar
    build:
      context: ./calendar
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./calendar:/app
    networks:
      - backend

  courses:
    container_name: courses
    build:
      context: ./courses
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./courses:/app
    networks:
      - backend

  authorisation:
    container_name: authorisation
    build:
      context: ./authorisation
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - courses
    volumes:
      - ./authorisation:/app
    networks:
      - backend


networks:
  backend:
    driver: bridge
