version: '2'
services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - courses
    volumes:
      - ./api-gateway:/app
    networks:
      - backend

  courses:
    container_name: courses
    build:
      context: ./courses
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./courses:/app
    networks:
      - backend

networks:
  backend:
    driver: bridge
