version: '2'
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - courses

  courses:
    build:
      context: ./courses
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

