name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies for API-Gateway
        run: npm install
        working-directory: API-Gateway

      - name: Install dependencies for Calendar
        run: npm install
        working-directory: Calendar

      - name: Install dependencies for Courses
        run: npm install
        working-directory: Courses

      - name: Build and run Docker Compose
        run: docker-compose -f /home/runner/work/Back-end/docker-compose.yml up -d --build

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Stop and remove containers
        run: docker-compose -f /home/runner/work/Back-end/docker-compose.yml down
