on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies for API-Gateway
      run: npm install
      working-directory: API-Gateway

    - name: Install dependencies for Calendar
      run: npm install
      working-directory: Calendar

    - name: Install dependencies for Courses
      run: npm install
      working-directory: Courses

    - name: Navigate to the root directory
      run: cd ..

    - name: Debugging information before Docker Compose
      run: |
        ls -la
        pwd

    - name: Build and run Docker Compose
      run: docker-compose up -d --build

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Stop and remove containers
      run: docker-compose down

