name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies for api-Gateway
      run: npm install
      working-directory: api-gateway

    - name: Install dependencies for Calendar
      run: npm install
      working-directory: calendar

    - name: Install dependencies for Courses
      run: npm install
      working-directory: courses

    - name: Install dependencies for Notification
      run: npm install
      working-directory: notification

    - name: Debugging information before Docker Compose
      run: |
        ls -la
        pwd

    - name: Build and run Docker Compose
      run: docker-compose up -d --build

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Stop and remove containers
      run: docker-compose down

