name: Build Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build API-Gateway Docker image
      run: docker build -t api-gateway ./API-Gateway

    - name: Build Calendar Docker image
      run: docker build -t calendar ./Calendar

    - name: Build Courses Docker image
      run: docker build -t courses ./Courses

    - name: Build Notifications Docker image
      run: docker build -t notifications ./Notifications

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Remove locally built Docker images
      run: |
        docker rmi -f api-gateway calendar courses notifications
